events {}

http {
    include /etc/nginx/mime.types;

    proxy_cache_path /tmp/cache keys_zone=my_cache:10m;

    upstream backend_api {
        server api-a:3000;
        server api-b:3000;
    }

    server {
        listen 80;

        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /api/ {
            proxy_pass http://backend_api/;
        }

        location = /api/stats {
            proxy_cache my_cache;
            proxy_cache_valid 200 30s;

            add_header X-Cache-Status $upstream_cache_status;

            proxy_pass http://backend_api/stats;
        }
    }
}