events {}

http {
    include /etc/nginx/mime.types;

    proxy_cache_path /tmp/cache keys_zone=mycache:10m;

    server {
        listen 80;

        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /api/ {
            proxy_pass http://backend-4-2-1:3000/;
        }

        location /api/stats {
            proxy_pass http://backend-4-2-1:3000/stats;

            proxy_cache mycache;
            proxy_cache_valid 200 30s;

            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}